---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/code-server --version
    register: code_server_test_output
  - debug:
      msg: '{{ code_server_test_output.stdout }}'
