---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ codeserver_install_dir }}...
  become: true
  stat:
    path: '{{ codeserver_install_dir }}'
  changed_when: False
  register: codeserver_binary
- when: not codeserver_binary.stat.exists
  block:
    - name: downloading {{ codeserver_url }}...
      become: true
      become_user: root
      get_url:
        url: '{{ codeserver_url }}'
        dest: '{{ codeserver_tmp_archive }}'
        checksum: '{{ codeserver_checksum }}'
        mode: 0644
    - name: unarchiving {{ codeserver_tmp_archive }}
      become: true
      unarchive:
        remote_src: true
        src: '{{ codeserver_tmp_archive }}'
        dest: '{{ codeserver_parent_install_dir }}'
        creates: '{{ codeserver_install_dir }}'
  always:
    - name: removing {{ codeserver_tmp_archive }}...
      become: true
      become_user: root
      file:
        path: '{{ codeserver_tmp_archive }}'
        state: absent
- name: linking binaries in {{ codeserver_parent_install_dir }}/bin to binaries in {{ codeserver_install_dir }}/bin
  become: true
  become_user: root
  with_items:
    - code-server
  file:
    src: '{{ codeserver_install_dir }}/bin/{{ item }}'
    dest: '{{ codeserver_parent_install_dir }}/bin/{{ item }}'
    state: link
